# Generated by Django 5.0.7 on 2024-08-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_draft',
        ),
    ]
