# Generated by Django 5.0.7 on 2024-08-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_blogpost_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
